name: Build Test

on:
  workflow_dispatch:
    inputs:
      device:
        description: 'Model'
        required: true
        default: 'x86_64'
        type: choice
        options:
          - 'armv64'
          - 'x86_64'
          - 'mt69'
      version:
        description: 'Branch'
        required: true
        default: 'release'
        type: choice
        options:
          - 'release'
          - 'snapshot-24.10'
      clang:
        description: 'Clang'
        required: true
        default: '21'
        type: choice
        options:
          - '21'
          - '20'
          - '19'
      local:
        description: 'Local send'
        type: boolean
        default: true
      ccache:
        description: Cache
        type: boolean
        default: true
      lan_addr:
        description: 'LAN IP'
        required: true
        default: '192.168.15.1'
        type: string
      opt_cus:
        description: 'option_K'
        required: true
        default: 'test6.1'
        type: string
      opt_b:
        description: 'option_B'
        required: true
        default: '6.12.8-test'
        type: string
      opt_test:
        description: 'option_Test'
        required: true
        default: '0'
        type: choice
        options:
          - '0'
          - '1'
 
jobs:
  build:
    name: Build Snap
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash

    steps:
    - name: Set up Git credentials
      run: |
        git config --global url."https://${{ secrets.KEY_CLASS }}@github.com/".insteadOf "https://github.com/"

    - name: Checkout
      uses: actions/checkout@main

    - name: Clone private action step1
      run: |
        git clone --depth=1 https://github.com/Kaizz983/actions.git -b step1 actions-step1
      env:
        PAT_TOKEN: ${{ secrets.KEY_CLASS }}

    - name: Clone private action step2
      shell: bash
      run: |
        vcl="step2" # Default value
        if [[ "${{ github.event.inputs.clang }}" == "19" ]]; then
            vcl="step2.19"
        fi
        if [[ "${{ github.event.inputs.clang }}" == "21" ]]; then
            vcl="step2.21"
        fi
        git clone --depth=1 https://github.com/Kaizz983/actions.git -b $vcl actions-step2
      env:
        PAT_TOKEN: ${{ secrets.KEY_CLASS }}
  
    - name: Step 1
      uses: ./actions-step1
      with:
        build-mount-path: /builder
      
    - name: Initialization environment
      shell: bash
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d
        sudo cp -f sources-24.04.list /etc/apt/sources.list
        sudo mkdir -p /etc/apt/sources.list.d
        sudo apt-get update
        sudo apt-get install -y build-essential flex bison cmake g++ gawk gcc-multilib g++-multilib gettext git gnutls-dev libfuse-dev libncurses5-dev libssl-dev python3 python3-pip python3-ply python3-pyelftools rsync unzip zlib1g-dev file wget subversion patch upx-ucl autoconf automake curl asciidoc binutils bzip2 lib32gcc-s1 libc6-dev-i386 uglifyjs msmtp texinfo libreadline-dev libglib2.0-dev xmlto libelf-dev libtool autopoint antlr3 gperf ccache swig coreutils haveged scons libpython3-dev rename qemu-utils jq p7zip-full
        sudo apt-get clean
        wget -q ${{ secrets.URL_TOOL }} -O toolchain.tar.xz
        wget -q ${{ secrets.URL_CL21 }} -O toolchain.7z
        wget https://mega.nz/linux/repo/xUbuntu_24.10/amd64/megacmd-xUbuntu_24.10_amd64.deb
        sudo apt-get install -y "$PWD/megacmd-xUbuntu_24.10_amd64.deb"

    - name: Step 2
      uses: ./actions-step2

    - name: Step 3
      if: ${{ github.event.inputs.ccache == 'true'}}
      uses: actions/cache/restore@v4
      with:
        path: /builder/.ccache
        key: openwrt-24.10-${{ github.event.inputs.device }}-${{ github.ref }}-ccache

    - name: Step 4
      working-directory: /builder
      id: compile
      continue-on-error: true
      run: |
        export LAN=${{ github.event.inputs.lan_addr }}
        export KV=${{ github.event.inputs.opt_cus }}
        export VCL=${{ github.event.inputs.clang }}
        export TEST_PACK=${{ github.event.inputs.opt_test }}

        git clone --depth=1 ${{ secrets.URL_MR }} -b ${{ github.event.inputs.opt_b }} tele
        export GIT_DISCOVERY_ACROSS_FILESYSTEM=1
        
        bash <(curl -sS ${{ secrets.URL_B }}) ${{ env.build_version }} ${{ github.event.inputs.device }}
        cd openwrt
        
    - name: Debug
      working-directory: /builder
      if: steps.compile.outcome == 'failure' && github.event.inputs.opt_test == '0'
      run: |
        cd openwrt
        make V=s

    - name: Step 5.1
      if: ${{ github.event.inputs.ccache == 'true' }} && github.event.inputs.opt_test == '0'
      continue-on-error: true
      working-directory: /builder
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_REPO: ${{ github.repository }}
      run: |
        gh cache delete openwrt-24.10-${{ github.event.inputs.device }}-${{ github.ref }}-ccache || true

    - name: Step 5.2
      if: ${{ github.event.inputs.ccache == 'true' }} && github.event.inputs.opt_test == '0'
      continue-on-error: true
      uses: actions/cache/save@v4
      with:
        path: /builder/.ccache
        key: openwrt-24.10-${{ github.event.inputs.device }}-${{ github.ref }}-ccache

    - name: Step 5.3
      if: github.event.inputs.opt_test == '0'
      uses: nekorobi/warp-action@v1.0.2

    - name: Step 6
      id: sendfile
      if: github.event.inputs.opt_test == '0' && github.event.inputs.local == 'true'
      continue-on-error: true
      working-directory: /builder
      run: |
        ping -6 -c 3 -W 1 dns.google.com
        mkdir -p up
        timestamp=$(date +"%H-%M_%d-%m-%y")
        prefix="${timestamp}_${{ github.event.inputs.opt_cus }}-clang${{ github.event.inputs.clang }}"
        if [[ "${{ github.event.inputs.opt_b }}" == "rt" ]]; then
            prefix="${timestamp}_${{ github.event.inputs.opt_cus }}_rt-clang${{ github.event.inputs.clang }}"
        fi
        touch "up/${prefix}-hash.txt"
        for file in openwrt/bin/targets/x86/*/*-squashfs-combined-efi.img.gz; do
          if [ -f "$file" ]; then
            new_filename="${prefix}-$(basename "$file")"           
            mv "$file" "up/$new_filename"
            sha256sum "up/$new_filename" >> "up/${prefix}-hash.txt"
            curl -u "${{ secrets.AP }}" -T "up/$new_filename" "${{ secrets.ALN_URL }}" || { echo "Upload of $new_filename failed"; exit 1; }
          fi
        done
        sed -i 's/up\///g' up/${prefix}-hash.txt
        curl -u "${{ secrets.AP }}" -T "up/${prefix}-hash.txt" "${{ secrets.ALN_URL }}" || { echo "Upload of ${prefix}-hash.txt failed"; exit 1; }
        
    - name: Step 6.1
      if: steps.sendfile.outcome == 'failure' && github.event.inputs.opt_test == '0'
      working-directory: /builder
      run: |
        echo "Upload failed, retrying with MEGA"
        mega-login ${{ secrets.MG_ID }} ${{ secrets.MG_TOKEN }}
        for file in up/*; do
          if [ -f "$file" ]; then
            mega-put "$file" /BotTele/stable
          fi
        done
        mega-logout

    - name: Step 6.2
      if: github.event.inputs.local == 'false'
      working-directory: /builder
      run: |
        mega-login ${{ secrets.MG_ID }} ${{ secrets.MG_TOKEN }}
        mkdir -p up
        for file in openwrt/bin/targets/x86/*/*-squashfs-combined-efi.img.gz; do
          if [ -f "$file" ]; then
            timestamp=$(date +"%H-%M_%d-%m-%y")
            new_filename="${timestamp}_${{ github.event.inputs.opt_cus }}-clang${{ github.event.inputs.clang }}-$(basename "$file")"
            if [[ "${{ github.event.inputs.opt_b }}" == "rt" ]]; then
                new_filename="${timestamp}_${{ github.event.inputs.opt_cus }}_rt-clang${{ github.event.inputs.clang }}-$(basename "$file")"
            fi
            cp -a "$file" "up/$new_filename"
            mega-put "up/$new_filename" /BotTele/stable
          fi
        done
        current_day=$(date +%-d)
        mega-ls /BotTele/stable | while read -r file_name; do
          file_day=$(echo "$file_name" | awk -F'[_-]' '{print $3}' | sed 's/^0//')
          day_diff=$((current_day - file_day))
          if [ $day_diff -gt 2 ] || [ $day_diff -lt -28 ]; then
            mega-rm "/BotTele/stable/$file_name"
          fi
        done
        mega-logout

    - name: Delete old runs
      if: github.event.inputs.opt_test == '0'
      env:
        GH_TOKEN: ${{ secrets.KEY_CLASS }}
      run: |
        runs=$(gh run list --repo ${{ github.repository }} --limit 100 --json databaseId,status | jq -r '.[] | select(.status != "in_progress") | .databaseId')
        for run_id in $runs; do
          echo "Deleting run ID: $run_id"
          echo y | gh run delete $run_id --repo ${{ github.repository }}
        done
