name: Build Snap

on:
  workflow_dispatch:
    inputs:
      device:
        description: 'Model'
        required: true
        default: 'x86_64'
        type: choice
        options:
          - 'armv64'
          - 'x86_64'
      version:
        description: 'Branch'
        required: true
        default: 'snapshot-24.10'
        type: choice
        options:
        #  - 'release'
          - 'snapshot-24.10'
      ccache:
        description: Cache
        type: boolean
        default: true
      lan_addr:
        description: 'LAN IP'
        required: true
        default: '192.168.15.1'
        type: string

jobs:
  build:
    name: Build Snap
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash

    steps:
    - name: Set up Git credentials
      run: |
        git config --global url."https://${{ secrets.KEY_CLASS }}@github.com/".insteadOf "https://github.com/"

    - name: Checkout
      uses: actions/checkout@main

    - name: Clone private action step1
      run: |
        git clone --depth=1 https://github.com/Kaizz983/actions.git -b step1 actions-step1
      env:
        PAT_TOKEN: ${{ secrets.KEY_CLASS }}

    - name: Clone private action step2
      shell: bash
      run: |
        vcl="step2" # Default value
        if [[ "${{ github.event.inputs.clang }}" == "19" ]]; then
            vcl="step2.19"
        fi
        git clone --depth=1 https://github.com/Kaizz983/actions.git -b $vcl actions-step2
      env:
        PAT_TOKEN: ${{ secrets.KEY_CLASS }}
        
    - name: Initialization environment
      shell: bash
      env:
        DEBIAN_FRONTEND: noninteractive
        GH_TOKEN: ${{ secrets.KEY_CLASS }}
      run: |
        gh release download -R
        curl -L \
             -H "Accept: application/octet-stream" \
             -H "Authorization: Bearer ${{ secrets.KEY_CLASS }}" \
                "${{ secrets.URL_TOOL2 }}" -o "toolchain.tar.xz"
        wget https://mega.nz/linux/repo/xUbuntu_24.10/amd64/megacmd-xUbuntu_24.10_amd64.deb
        sudo apt-get install -y "$PWD/megacmd-xUbuntu_24.10_amd64.deb"
        
    - name: Step 2
      uses: ./actions-step2
