name: Build Snap

on:
  workflow_dispatch:
    inputs:
      device:
        description: 'Model'
        required: true
        default: 'x86_64'
        type: choice
        options:
          - 'armv64'
          - 'x86_64'
      version:
        description: 'Branch'
        required: true
        default: 'snapshot-24.10'
        type: choice
        options:
        #  - 'release'
          - 'snapshot-24.10'
      ccache:
        description: Cache
        type: boolean
        default: true
      lan_addr:
        description: 'LAN IP'
        required: true
        default: '192.168.15.1'
        type: string

jobs:
  build:
    name: Build Snap
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash

    steps:
    - name: Set up Git credentials
      run: |
        git config --global url."https://${{ secrets.KEY_CLASS }}@github.com/".insteadOf "https://github.com/"

    - name: Checkout
      uses: actions/checkout@main

    - name: Clone private action step1
      run: |
        git clone --depth=1 https://github.com/Kaizz983/actions.git -b step1 actions-step1
      env:
        PAT_TOKEN: ${{ secrets.KEY_CLASS }}

    - name: Clone private action step2
      shell: bash
      run: |
        vcl="step2" # Default value
        if [[ "${{ github.event.inputs.clang }}" == "19" ]]; then
            vcl="step2.19"
        fi
        git clone --depth=1 https://github.com/Kaizz983/actions.git -b $vcl actions-step2
      env:
        PAT_TOKEN: ${{ secrets.KEY_CLASS }}

    - name: Initialization environment
      shell: bash
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d
        sudo cp -f sources-24.04.list /etc/apt/sources.list
        sudo mkdir -p /etc/apt/sources.list.d
        sudo apt-get update
        sudo apt-get install -y build-essential flex bison cmake g++ gawk gcc-multilib g++-multilib gettext git gnutls-dev libfuse-dev libncurses5-dev libssl-dev python3 python3-pip python3-ply python3-pyelftools rsync unzip zlib1g-dev file wget subversion patch upx-ucl autoconf automake curl asciidoc binutils bzip2 lib32gcc-s1 libc6-dev-i386 uglifyjs msmtp texinfo libreadline-dev libglib2.0-dev xmlto libelf-dev libtool autopoint antlr3 gperf ccache swig coreutils haveged scons libpython3-dev rename qemu-utils jq p7zip-full
        sudo apt-get clean

    - name: Install, connect WARP
      uses: nekorobi/warp-action@v1.0.2
        
    - name: IPv6 ping
      shell: bash
      working-directory: /builder
      run: |
        ping -6 -c 3 -W 1 google.com
        mkdir -p up
        cd up
        echo "Hello World" > hello.txt
        curl -u "${{ secrets.AP }}" -T hello.txt "${{ secrets.ALN_URL }}"

